### ISSUE TITLE
Allow time 1.5

### ISSUE THREAD

**Issue by hesselink** [hdbc/hdbc#27]
GHC 7.10 has a release candidate out now, and includes time 1.5 as a base library. It would be very nice if there was a version of HDBC that supported time 1.5, and that would allow us to test our packages that depend on it with GHC 7.10.

**Comment by ulricha** [comment]
The current HDBC HEAD (0504c4e61) builds fine with GHC 7.10.1 RC3. Simply releasing that would help a lot.

**Comment by bos** [comment]
@hesselink, you're the only remotely active maintainer on this project. Want to push out a release?

**Comment by hesselink** [comment]
@bos Yes, I meant to do that, but it slipped through the cracks, sorry. I've just released HDBC-2.4.0.1.
