### ISSUE TITLE
prepare returns IO Statement, but functions want Statement

### ISSUE THREAD

**Issue by jstr045329** [hdbc/hdbc#47]
I'm new to Haskell and trying to connect to query a postgresql database.

I succeeded in making a connection and running quickQuery.

I succeeded in using prepare to make a query:

λ>   selStmt = "SELECT blah blah blach FROM tablename;"

λ>   prepStmt = Database.HDBC.prepare conn selStmt

That works.

λ>   :t prepStmt 
prepStmt  :: IO Statement

All the functions that do things with statements want a Statement, not IO Statement. 

I must be missing something.

How do I either 1) transform the IO Statement into a Statement (seems unsafe from what I've read), or 2) transform all the functions expecting a Statement to expect IO Statement?

**Comment by rsoeldner** [comment]
@jstr045329 I suggest looking at http://learnyouahaskell.com/a-fistful-of-monads#do-notation for example and check https://github.com/hdbc/hdbc-postgresql/blob/master/testsrc/TestMisc.hs
